#!/usr/bin/env python3
"""
CloudScale — PostgreSQL OLTP Extractor (Phase 4)
=================================================
Simulates a batch extraction from the legacy PostgreSQL OLTP database
(orders and merchants tables), reading from the synthetic data files
generated in Phase 2 and landing them idempotently into the Bronze zone.

In production this would connect to:
    postgresql+psycopg2://{host}:{port}/{db}
    and execute: SELECT * FROM orders WHERE date_trunc('day', order_timestamp) = {logical_date}

Locally it reads from:
    data/raw/postgres_orders/dt={date}/   (orders CSV)
    data/raw/postgres_merchants/           (merchants CSV, full extract)

Landing strategy:
    - Orders:    Partitioned by order date → data/bronze/postgres_orders/dt={date}/
    - Merchants: Daily snapshot           → data/bronze/postgres_merchants/dt={date}/
"""

from __future__ import annotations

import argparse
import json
import logging
import sys
from datetime import datetime, timezone
from pathlib import Path

# Allow running from project root
PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from ingestion.bronze_lander import land_file, land_directory  # noqa: E402

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s — %(message)s",
)
logger = logging.getLogger("extract_postgres")

SOURCE_ORDERS = "postgres_orders"
SOURCE_MERCHANTS = "postgres_merchants"


def extract_orders(
    source_raw: Path,
    bronze_root: Path,
    partition_date: str,
    overwrite: bool = False,
) -> list:
    """
    Extract and land the orders CSV file for the given partition date.

    Source path convention (generated by Phase 2):
        {source_raw}/postgres_orders/dt={date}/orders_{YYYYMMDD}.csv

    Args:
        source_raw:      Root of the raw source data (e.g. data/raw).
        bronze_root:     Bronze landing zone root (e.g. data/bronze).
        partition_date:  Target date string YYYY-MM-DD.
        overwrite:       Force re-land even if checksum matches.

    Returns:
        List of ingestion result dicts.
    """
    source_partition_dir = source_raw / SOURCE_ORDERS / f"dt={partition_date}"

    if not source_partition_dir.exists():
        logger.warning(
            f"[WARN] No source orders data found for dt={partition_date} "
            f"at {source_partition_dir}. Run data_generator first."
        )
        return []

    logger.info(
        f"Extracting PostgreSQL orders for partition dt={partition_date} "
        f"from {source_partition_dir}"
    )

    results = land_directory(
        source_dir=source_partition_dir,
        bronze_root=bronze_root,
        source_name=SOURCE_ORDERS,
        partition_date=partition_date,
        file_extensions=(".csv",),
        file_type="csv",
        overwrite=overwrite,
    )

    total_records = sum(
        r.get("records_landed", 0) for r in results if r.get("records_landed", 0) > 0
    )
    logger.info(
        f"Orders extraction complete: {len(results)} file(s) processed, "
        f"{total_records} records landed."
    )
    return results


def extract_merchants(
    source_raw: Path,
    bronze_root: Path,
    partition_date: str,
    overwrite: bool = False,
) -> list:
    """
    Extract and land a date-partitioned snapshot of the merchants master CSV.

    Source path convention (generated by Phase 2):
        {source_raw}/postgres_merchants/merchants.csv

    Merchants are a slowly-changing dimension — we re-verify the checksum on
    each run and skip if unchanged. Changed snapshots require a new partition
    or explicit overwrite.

    Args:
        source_raw:      Root of the raw source data.
        bronze_root:     Bronze landing zone root.
        partition_date:  Snapshot partition date (YYYY-MM-DD).
        overwrite:       Force re-land.

    Returns:
        List of ingestion result dicts.
    """
    merchants_file = source_raw / SOURCE_MERCHANTS / "merchants.csv"

    if not merchants_file.exists():
        logger.warning(
            f"[WARN] Merchants source file not found at {merchants_file}. "
            "Run data_generator first."
        )
        return []

    logger.info(f"Extracting PostgreSQL merchants from {merchants_file}")

    # Preserve each daily master snapshot in its own immutable partition.
    result = land_file(
        source_path=merchants_file,
        bronze_root=bronze_root,
        source_name=SOURCE_MERCHANTS,
        partition_date=partition_date,
        file_type="csv",
        overwrite=overwrite,
    )

    logger.info(
        f"Merchants extraction complete: {result['status']} — "
        f"{result.get('records_landed', '?')} records."
    )
    return [result]


def run(
    partition_date: str,
    bronze_root: Path,
    source_raw: Path,
    overwrite: bool = False,
) -> dict:
    """
    Run the full PostgreSQL extraction for a given logical date.

    Args:
        partition_date:  YYYY-MM-DD date string (Airflow logical_date).
        bronze_root:     Bronze landing zone root directory.
        source_raw:      Source raw data root directory.
        overwrite:       Force overwrite flag.

    Returns:
        Summary dict with statuses and record counts.
    """
    logger.info(f"=== PostgreSQL Extractor START | partition_date={partition_date} ===")

    orders_results = extract_orders(source_raw, bronze_root, partition_date, overwrite)
    merchants_results = extract_merchants(
        source_raw, bronze_root, partition_date, overwrite
    )

    all_results = orders_results + merchants_results
    summary = {
        "extractor": "extract_postgres",
        "partition_date": partition_date,
        "run_timestamp": datetime.now(timezone.utc).isoformat(),
        "files_processed": len(all_results),
        "files_landed": sum(
            1 for r in all_results if r.get("status") in ("landed", "overwritten")
        ),
        "files_skipped": sum(1 for r in all_results if r.get("status") == "skipped"),
        "total_records": sum(
            r.get("records_landed", 0)
            for r in all_results
            if isinstance(r.get("records_landed"), int) and r["records_landed"] > 0
        ),
        "results": all_results,
    }

    logger.info(
        f"=== PostgreSQL Extractor DONE | "
        f"landed={summary['files_landed']}, skipped={summary['files_skipped']}, "
        f"records={summary['total_records']} ==="
    )
    return summary


def main():
    parser = argparse.ArgumentParser(
        description="CloudScale — PostgreSQL OLTP Extractor (Bronze Landing)"
    )
    parser.add_argument(
        "--date",
        type=str,
        default=datetime.now(timezone.utc).strftime("%Y-%m-%d"),
        help="Partition date YYYY-MM-DD (default: today UTC)",
    )
    parser.add_argument(
        "--bronze-root",
        type=str,
        default="data/bronze",
        help="Bronze landing zone root directory (default: data/bronze)",
    )
    parser.add_argument(
        "--source-raw",
        type=str,
        default="data/raw",
        help="Source raw data root (default: data/raw)",
    )
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Force re-land even if the file is already present with a matching checksum",
    )
    args = parser.parse_args()

    bronze_root = PROJECT_ROOT / args.bronze_root
    source_raw = PROJECT_ROOT / args.source_raw

    summary = run(
        partition_date=args.date,
        bronze_root=bronze_root,
        source_raw=source_raw,
        overwrite=args.overwrite,
    )
    print(json.dumps(summary, indent=2))


if __name__ == "__main__":
    main()
